# Travis CI integration -- https://travis-ci.org/troglobit/finit
# Defaults to GNU GCC and autotools: ./configure && make && make test
language: c

# Use docker for quicker builds, it now allows https://docs.travis-ci.com/user/apt/
sudo: false

# Test build only with both GCC for the moment
compiler:
  - gcc
  - clang

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "i2bwQa4I+mluvfBk95snxKntMfEIwtXrDYUATcnCJ82vhFjl9pwiy0WSeZgNOj9n2z9p0J0yT7qyvI1z/yqQbZ1ZaeJ0R9SMOQvZZ+gEEHf3o2XdGII+BnsgByWNyu9TGkTp2gco81Annz1P48/sbMlHlcfnq/mHh+wbdm4SexD5uUGPoCIErRObFCGi6VQMbgYHCFTH4z0eVKAb8fabhv78za3/H5fNsljsXwSt63Jn+VhJTCkyts0etz5I7eXlxjAVe5hAXQJughCC0NBS4ZmmAzf2evc9DXjQk24Oq5k8XGYsKGIi9n4hmZGLTTjpC5eYwzrGOjEII0v7bxIWH2d7bIzlLl9LJoGEcM9XBDY7KRK3e/o5ozxo2mCao9lM3gffZUsuSMjIuOmNfpTUP4VvB2fgALPl5towA8QnWc97MueSimJcVZ+bRpKrja79Zke+5LQjnzzOMhOUAn5EZ1sVDaSUR9fS4Q8iaHs99AEaWrkYMpsQQbKAcV5BucPFfsMXGArEwo+nWSwPEgvGkHs4L/wiR+oDkbfjYKSz5g/PhVFh4nN6rEmsx4Q77Um+OLkR/MR9+KDP5JBiB09BkLS6jfJYzst3dJPbmNEDcMJXeQ/JGnt2ld8xbYBezNi0Ef/o06IeBzA1HVDVCTmFwaTBtENu6Pojr11OgeynX18="

addons:
  apt:
    packages:
      - tree
  coverity_scan:
    project:
      name: "troglobit/redir"
      description: "A TCP port redirector for UNIX"
    notification_email: troglobit@gmail.com
    build_command_prepend: "./autogen.sh && ./configure"
    build_command:      "make"
    branch_pattern:     master

# Custom build script for the time being, no "make test" yet
script:
  - ./autogen.sh
  - ./configure --prefix=/tmp
  - make clean
  - make -j5 V=1
  - make install-strip
  - tree /tmp
  - ldd /tmp/bin/redir
  - size /tmp/bin/redir
  - /tmp/bin/redir -h
